version: "3.3"

services:

  # http://serveis.bcn.coop
  coopolis:
    restart: on-failure
    container_name: ateneu_coopolis # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_production
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8000:8000
    depends_on:
      - db
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  coopolis-automation:
    restart: on-failure
    container_name: coopolis_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_production
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - coopolis

  # http://ateneu-demo.codi.coop
  ateneu-demo:
    restart: on-failure
    container_name: ateneu_demo
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-demo
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8001 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8001:8001
    depends_on:
      - db

  # https://serveis.coopcamp.cat
  ateneu-coopcamp:
    restart: on-failure
    container_name: ateneu_coopcamp # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopcamp
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8002 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8002:8002
    depends_on:
      - db

  coopcamp-automation:
    restart: on-failure
    container_name: coopcamp_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopcamp
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-coopcamp

  # https://serveis.coopmaresme.cat
  ateneu-coopmaresme:
    restart: on-failure
    container_name: ateneu_coopmaresme # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopmaresme
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8003 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8003:8003
    depends_on:
      - db

  coopmaresme-automation:
    restart: on-failure
    container_name: coopmaresme_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopmaresme
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-coopmaresme

  # https://serveis.ateneubnord.cat
  ateneu-bnord:
    restart: on-failure
    container_name: ateneu_bnord # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-bnord
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8004 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8004:8004
    depends_on:
      - db

  bnord-automation:
    restart: on-failure
    container_name: bnord_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-bnord
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-bnord

  # https://serveis.ponentcoopera.cat
  # Ens saltem el port 8005 perquè hi ha l'antic back-office (java) allà.
  ateneu-ponentcoopera:
    restart: on-failure
    container_name: ateneu_ponentcoopera # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-ponentcoopera
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8006 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8006:8006
    depends_on:
      - db

  ponentcoopera-automation:
    restart: on-failure
    container_name: ponentcoopera_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-ponentcoopera
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-ponentcoopera

  # https://serveis.ateneucooperatiuvalles.org
  ateneu-vallesoccidental:
    restart: on-failure
    container_name: ateneu_vallesoccidental # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-vallesoccidental
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8007 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8007:8007
    depends_on:
      - db

  vallesoccidental-automation:
    restart: on-failure
    container_name: vallesoccidental_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-vallesoccidental
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-vallesoccidental

  # https://serveis.coopcatcentral.cat
  ateneu-catcentral:
    restart: on-failure
    container_name: ateneu_catcentral # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-catcentral
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8008 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8008:8008
    depends_on:
      - db

  catcentral-automation:
    restart: on-failure
    container_name: catcentral_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-catcentral
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-catcentral

  # https://serveis.coopsetania.cat
  # Nota: no té el port 8009 perquè l'ocupa el java
  ateneu-coopsetania:
    restart: on-failure
    container_name: ateneu_coopsetania # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopsetania
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8010 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8010:8010
    depends_on:
      - db

  coopsetania-automation:
    restart: on-failure
    container_name: coopsetania_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopsetania
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-coopsetania

  # https://serveis.ateneucoopgi.org
  ateneu-terresgironines:
    restart: on-failure
    container_name: ateneu_terresgironines # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-terresgironines
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8011 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8011:8011
    depends_on:
      - db

  terresgironines-automation:
    restart: on-failure
    container_name: terresgironines_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-terresgironines
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-terresgironines

  # https://serveis.ateneulh.coop
  ateneu-hospitalet:
    restart: on-failure
    container_name: ateneu_hospitalet # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-hospitalet
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8012 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8012:8012
    depends_on:
      - db

  hospitalet-automation:
    restart: on-failure
    container_name: hospitalet_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-hospitalet
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-hospitalet

  # https://serveis.ateneucoopte.org
  ateneu-terresebre:
    restart: on-failure
    container_name: ateneu_terresebre # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-terresebre
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8013 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8013:8013
    depends_on:
      - db

  terresebre-automation:
    restart: on-failure
    container_name: terresebre_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-terresebre
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-terresebre

  # https://serveis.acapa.cat
  ateneu-altpirineu:
    restart: on-failure
    container_name: ateneu_altpirineu # If changed, update ofelia config and db backups script
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-altpirineu
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8014 --timeout 300 # Sense el timeout peta i l'apache dona proxy error
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8014:8014
    depends_on:
      - db

  altpirineu-automation:
    restart: on-failure
    container_name: altpirineu_automation
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-altpirineu
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
      - ateneu-altpirineu

  # https://documentacio-backoffice.bcn.coop
  documentacio:
    restart: on-failure
    container_name: documentacio
    image: requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_NAME: documentacio_wikijs
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - /srv/postgres-data/coopolis-production:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword