version: "3.5"

networks:
  develop_ateneus_network:
    name: develop_ateneus_network

services:

  # http://ateneus-develop.codi.coop:5001
  ateneu-coopolis:
    container_name: develop_ateneus_coopolis # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopolis
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
    #entrypoint: ["sh", "-c", "sleep 2073600"]
  ateneu-coopolis-automation:
    container_name: develop_automation_coopolis
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopolis
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  # http://ateneus-develop.codi.coop:5002
  ateneu-coopcamp:
    container_name: develop_ateneus_coopcamp # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopcamp
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-coopcamp-automation:
    container_name: develop_automation_coopcamp # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopcamp
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5003
  ateneu-coopmaresme:
    container_name: develop_ateneus_coopmaresme # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopmaresme
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-coopmaresme-automation:
    container_name: develop_automation_coopmaresme # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopmaresme
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5004
  ateneu-bnord:
    container_name: develop_ateneus_bnord # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-bnord
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-bnord-automation:
    container_name: develop_automation_bnord # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-bnord
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5005
  ateneu-ponentcoopera:
    container_name: develop_ateneus_ponentcoopera # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-ponentcoopera
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-ponentcoopera-automation:
    container_name: develop_automation_ponentcoopera # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-ponentcoopera
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5006
  ateneu-vallesoccidental:
    container_name: develop_ateneus_vallesoccidental # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-vallesoccidental
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-vallesoccidental-automation:
    container_name: develop_automation_vallesoccidental # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-vallesoccidental
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5007
  ateneu-catcentral:
    container_name: develop_ateneus_catcentral # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-catcentral
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-catcentral-automation:
    container_name: develop_automation_catcentral # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-catcentral
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5008
  ateneu-coopsetania:
    container_name: develop_ateneus_coopsetania # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopsetania
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-coopsetania-automation:
    container_name: develop_automation_coopsetania # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-coopsetania
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5009
  ateneu-terresgironines:
    container_name: develop_ateneus_terresgironines # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-terresgironines
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-terresgironines-automation:
    container_name: develop_automation_terresgironines # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-terresgironines
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5010
  ateneu-hospitalet:
    container_name: develop_ateneus_hospitalet # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-hospitalet
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-hospitalet-automation:
    container_name: develop_automation_hospitalet # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-hospitalet
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5011
  ateneu-terresebre:
    container_name: develop_ateneus_terresebre # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-terresebre
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-terresebre-automation:
    container_name: develop_automation_terresebre # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-terresebre
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  # http://ateneus-develop.codi.coop:5012
  ateneu-altpirineu:
    container_name: develop_ateneus_altpirineu # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-altpirineu
      - PYTHONPATH=/shared_libraries
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network
  ateneu-altpirineu-automation:
    container_name: develop_automation_altpirineu # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=develop_ateneus_db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=docker-develop.django-settings.ateneu-altpirineu
      - PYTHONPATH=/shared_libraries
    command: python manage.py qcluster
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - develop_ateneus_db
    networks:
      - develop_ateneus_network

  develop_ateneus_db:
    container_name: develop_ateneus_db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - develop_ateneus_network

  develop_ateneus_nginx:
    container_name: develop_ateneus_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../:/srv
    ports:
       - 5001-5012:81-92
#      - 5001:81 # Coòpolis
#      - 5002:82 # Coopcamp
#      - 5003:83 # CoopMaresme
#      - 5004:84 # Barcelonès Nord
#      - 5005:85 # PonentCoopera
#      - 5006:86 # Vallès Occidental
#      - 5007:87 # Catalunya Central
#      - 5008:88 # Coopsetània
#      - 5009:89 # Terres Gironines
#      - 5010:90 # Hospitalet
#      - 5011:91 # Terres de l'Ebre
#      - 5012:92 # Alt Pirineu i Aran
    depends_on:
      - ateneu-coopolis
    networks:
      - develop_ateneus_network

#  ofelia:
#    container_name: develop_coopolis_ofelia
#    image: 'mcuadros/ofelia:latest'
#    volumes:
#      - ./ofelia/config.ini:/etc/ofelia/config.ini
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - ateneu-coopolis
#    networks:
#      - develop_ateneus_network
